language: ruby

sudo: false

before_install:
  - gem install bundler -v 1.12.5

cache: bundler

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1

addons:
  code_climate:
    repo_token: 1b39b043a2eb317b3e8202eb459c71af2899d7b43e884e9a4d7b124489446f42
